version: '2'
services:
#  web:
#    build: .
#    ports:
#     - "5000:5000"
#    volumes:
#     - .:/code
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - "db:/var/lib/postgresql/data"
volumes:
  db:

