version: '2'
services:
  database:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - "database:/var/lib/postgresql/data"
  server-side-app:
    build: "server/"
    command: "/opt/bullet/runtime/bin/web-server"
    volumes:
      - "./server:/opt/bullet"
    depends_on:
      - database
    links:
      - "database"
    env_file: "dev.env"
  reverse-proxy:
    build: "reverse-proxy"
    links:
    - "server-side-app:web-app-server"
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - "server-side-app"
    volumes_from:
    - "server-side-app"
volumes:
  database:

