version: '2'
services:
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - "db:/var/lib/postgresql/data"
  web:
    build: "server/"
    command: "/code/server/runtime/bin/web-server"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: "dev.env"
volumes:
  db:

