version: '2'
services:
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
  server-side-app:
    build: server
    command: /opt/bullet/runtime/bin/web-server
    volumes:
      - ./server:/opt/bullet
    depends_on:
      - database
    links:
      - database
    env_file: .env
  client-side-app:
    build: client
    command: ng build --watch -o /var/www
    volumes:
      - ./client:/opt/bullet
      - node_modules:/opt/bullet/node_modules
  reverse-proxy:
    build: reverse-proxy
    links:
    - server-side-app
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - server-side-app
      - client-side-app
    volumes_from:
      - server-side-app
      - client-side-app
volumes:
  database:
  node_modules:

