# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_auto_20170124_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('POS', 'postponed'), ('SCH', 'scheduled')], max_length=3)),
                ('date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('FUT', 'future'), ('MON', 'monthly'), ('WEE', 'weekly'), ('DAI', 'daily'), ('COL', 'collection')], max_length=3)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
    ]
