# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signifiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=16384)),
                ('type', models.CharField(choices=[('TASK', 'task'), ('EVNT', 'event'), ('NOTE', 'note')], max_length=4)),
                ('complete', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSignifierRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('signifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signifiers.Signifier')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='signifier',
            field=models.ManyToManyField(through='items.ItemSignifierRelationship', to='signifiers.Signifier'),
        ),
        migrations.AlterUniqueTogether(
            name='itemsignifierrelationship',
            unique_together=set([('signifier', 'item')]),
        ),
    ]
