# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='signifier',
            new_name='signifiers',
        ),
    ]
